return {
  name = "Gruvbox Light",
  mode = "light",
  palette = {
    bg0 = "#fbf1c7",
    bg1 = "#ebdbb2",
    bg2 = "#d5c4a1",
    bg3 = "#bdae93",
    fg1 = "#3c3836",
    gray = "#7c6f64",
    red = "#9d0006",
    green = "#79740e",
    yellow = "#b57614",
    blue = "#076678",
    purple = "#8f3f71",
    aqua = "#427b58",
    orange = "#af3a03",
  },
  highlights = {
    Normal = { fg = "fg1", bg = "bg0" },
    NormalFloat = { fg = "fg1", bg = "bg1" },
    FloatBorder = { fg = "gray", bg = "bg1" },
    CursorLine = { bg = "bg1" },
    CursorLineNr = { fg = "orange" },
    LineNr = { fg = "gray" },
    SignColumn = { bg = "bg0" },
    ColorColumn = { bg = "bg1" },
    Visual = { bg = "bg2" },
    Search = { fg = "bg0", bg = "yellow" },
    IncSearch = { fg = "bg0", bg = "orange" },
    Pmenu = { fg = "fg1", bg = "bg1" },
    PmenuSel = { fg = "bg0", bg = "orange" },
    StatusLine = { fg = "fg1", bg = "bg1" },
    StatusLineNC = { fg = "gray", bg = "bg1" },
    VertSplit = { fg = "gray", bg = "bg0" },
    WinSeparator = { fg = "gray", bg = "bg0" },
  },
}
