return {
  name = "Miasma",
  mode = "dark",
  palette = {
    base = "#222222",
    surface = "#222222",
    overlay = "#242d1d",
    selection = "#383838",
    muted = "#8a8a7e",
    text = "#c2c2b0",
    crimson = "#685742",
    cyan = "#c9a554",
    lightCyan = "#78824b",
    green = "#5f875f",
    yellow = "#b36d43",
    red = "#685742",
    purple = "#bb7744",
    orange = "#b36d43",
  },
  highlights = {
    Normal = { fg = "text", bg = "base" },
    NormalFloat = { fg = "text", bg = "surface" },
    FloatBorder = { fg = "muted", bg = "surface" },
    CursorLine = { bg = "surface" },
    CursorLineNR = { fg = "crimson" },
    LineNr = { fg = "muted" },
    SignColumn = { bg = "base" },
    ColorColumn = { bg = "surface" },
    Visual = { bg = "selection" },
    Search = { fg = "base", bg = "yellow" },
    IncSearch = { fg = "base", bg = "crimson" },
    Pmenu = { fg = "text", bg = "surface" },
    PmenuSel = { fg = "base", bg = "crimson" },
    StatusLine = { fg = "text", bg = "surface" },
    StatusLineNR = { fg = "muted", bg = "surface" },
    VertSplit = { fg = "muted", bg = "base" },
    WinSeparator = { fg = "muted", bg = "base" },
  },
}
