$background = rgb(f6f1ef)
$surface = rgb(ede4de)
$surface_raised = rgb(e5d9d1)
$surface_overlay = rgb(c9bab1)
$text = rgb(545464)
$text_muted = rgb(716e61)
$accent = rgb(5a7785)
$accent_muted = rgb(4d699b)
$accent_alt = rgb(6f894e)
$on_accent = rgb(f6f1ef)
$border = rgb(c9bab1)
$selection = rgb(e5d9d1)
$success = rgb(6f894e)
$warning = rgb(cc6d00)
$error = rgb(c84053)
$info = rgb(4e8ca2)
$shadow = rgb(f6f1ef)
