return {
  name = "Kanagawa Lotus",
  mode = "light",
  palette = {
    bg0 = "#f6f1ef",
    bg1 = "#ede4de",
    bg2 = "#e5d9d1",
    bg3 = "#c9bab1",
    fg1 = "#545464",
    gray = "#716e61",
    red = "#c84053",
    green = "#6f894e",
    yellow = "#cc6d00",
    blue = "#4e8ca2",
    purple = "#624c83",
    aqua = "#5e857a",
    orange = "#4d699b",
  },
  highlights = {
    Normal = { fg = "fg1", bg = "bg0" },
    NormalFloat = { fg = "fg1", bg = "bg1" },
    FloatBorder = { fg = "gray", bg = "bg1" },
    CursorLine = { bg = "bg1" },
    CursorLineNr = { fg = "orange" },
    LineNr = { fg = "gray" },
    SignColumn = { bg = "bg0" },
    ColorColumn = { bg = "bg1" },
    Visual = { bg = "bg3" },
    Search = { fg = "bg0", bg = "yellow" },
    IncSearch = { fg = "bg0", bg = "orange" },
    Pmenu = { fg = "fg1", bg = "bg1" },
    PmenuSel = { fg = "bg0", bg = "orange" },
    StatusLine = { fg = "fg1", bg = "bg1" },
    StatusLineNC = { fg = "gray", bg = "bg1" },
    VertSplit = { fg = "gray", bg = "bg0" },
    WinSeparator = { fg = "gray", bg = "bg0" },
  },
}
