pragma Singleton
import QtQuick

// Generated by matugen. Do not edit by hand.
QtObject {
    readonly property string mode: "#131318" === "#fff8f8" ? "light" : "auto"


    readonly property color background: "#131318"

    readonly property color error: "#ffb4ab"

    readonly property color error_container: "#93000a"

    readonly property color inverse_on_surface: "#303036"

    readonly property color inverse_primary: "#575992"

    readonly property color inverse_surface: "#e4e1e9"

    readonly property color on_background: "#e4e1e9"

    readonly property color on_error: "#690005"

    readonly property color on_error_container: "#ffdad6"

    readonly property color on_primary: "#292a60"

    readonly property color on_primary_container: "#e1e0ff"

    readonly property color on_primary_fixed: "#13144b"

    readonly property color on_primary_fixed_variant: "#3f4178"

    readonly property color on_secondary: "#2e2f42"

    readonly property color on_secondary_container: "#e2e0f9"

    readonly property color on_secondary_fixed: "#191a2c"

    readonly property color on_secondary_fixed_variant: "#454559"

    readonly property color on_surface: "#e4e1e9"

    readonly property color on_surface_variant: "#c8c5d0"

    readonly property color on_tertiary: "#46263a"

    readonly property color on_tertiary_container: "#ffd8ec"

    readonly property color on_tertiary_fixed: "#2e1125"

    readonly property color on_tertiary_fixed_variant: "#5f3c51"

    readonly property color outline: "#918f9a"

    readonly property color outline_variant: "#46464f"

    readonly property color primary: "#c0c1ff"

    readonly property color primary_container: "#3f4178"

    readonly property color primary_fixed: "#e1e0ff"

    readonly property color primary_fixed_dim: "#c0c1ff"

    readonly property color scrim: "#000000"

    readonly property color secondary: "#c6c4dd"

    readonly property color secondary_container: "#454559"

    readonly property color secondary_fixed: "#e2e0f9"

    readonly property color secondary_fixed_dim: "#c6c4dd"

    readonly property color shadow: "#000000"

    readonly property color source_color: "#303274"

    readonly property color surface: "#131318"

    readonly property color surface_bright: "#39383f"

    readonly property color surface_container: "#1f1f25"

    readonly property color surface_container_high: "#2a292f"

    readonly property color surface_container_highest: "#35343a"

    readonly property color surface_container_low: "#1b1b21"

    readonly property color surface_container_lowest: "#0e0e13"

    readonly property color surface_dim: "#131318"

    readonly property color surface_tint: "#c0c1ff"

    readonly property color surface_variant: "#46464f"

    readonly property color tertiary: "#e9b9d3"

    readonly property color tertiary_container: "#5f3c51"

    readonly property color tertiary_fixed: "#ffd8ec"

    readonly property color tertiary_fixed_dim: "#e9b9d3"


    // Frutiger Aero / cloudy accents derived from matugen tokens
    readonly property color glassTint:        Qt.rgba(primary_container.r, primary_container.g, primary_container.b, 0.35)
    readonly property color glassHighlight:   Qt.rgba(1, 1, 1, 0.55)
    readonly property color glassEdge:        Qt.rgba(1, 1, 1, 0.75)
    readonly property color glassShadow:      Qt.rgba(0, 0, 0, 0.18)
    readonly property color skyTop:           Qt.lighter(primary_container, 1.15)
    readonly property color skyBottom:        Qt.lighter(tertiary_container, 1.05)
    readonly property color accent:           primary
    readonly property color accentSoft:       inverse_primary
    readonly property color textPrimary:      on_surface
    readonly property color textMuted:        on_surface_variant
}
