pragma Singleton
import QtQuick

// Generated by matugen. Do not edit by hand.
QtObject {
    readonly property string mode: "#0e1514" === "#fff8f8" ? "light" : "auto"


    readonly property color background: "#0e1514"

    readonly property color error: "#ffb4ab"

    readonly property color error_container: "#93000a"

    readonly property color inverse_on_surface: "#2b3231"

    readonly property color inverse_primary: "#006a63"

    readonly property color inverse_surface: "#dde4e2"

    readonly property color on_background: "#dde4e2"

    readonly property color on_error: "#690005"

    readonly property color on_error_container: "#ffdad6"

    readonly property color on_primary: "#003733"

    readonly property color on_primary_container: "#9df2e8"

    readonly property color on_primary_fixed: "#00201d"

    readonly property color on_primary_fixed_variant: "#00504b"

    readonly property color on_secondary: "#1c3532"

    readonly property color on_secondary_container: "#cce8e4"

    readonly property color on_secondary_fixed: "#051f1d"

    readonly property color on_secondary_fixed_variant: "#324b48"

    readonly property color on_surface: "#dde4e2"

    readonly property color on_surface_variant: "#bec9c6"

    readonly property color on_tertiary: "#17324a"

    readonly property color on_tertiary_container: "#cee5ff"

    readonly property color on_tertiary_fixed: "#001d33"

    readonly property color on_tertiary_fixed_variant: "#2f4961"

    readonly property color outline: "#899391"

    readonly property color outline_variant: "#3f4947"

    readonly property color primary: "#81d5cc"

    readonly property color primary_container: "#00504b"

    readonly property color primary_fixed: "#9df2e8"

    readonly property color primary_fixed_dim: "#81d5cc"

    readonly property color scrim: "#000000"

    readonly property color secondary: "#b1ccc8"

    readonly property color secondary_container: "#324b48"

    readonly property color secondary_fixed: "#cce8e4"

    readonly property color secondary_fixed_dim: "#b1ccc8"

    readonly property color shadow: "#000000"

    readonly property color source_color: "#203c39"

    readonly property color surface: "#0e1514"

    readonly property color surface_bright: "#343a39"

    readonly property color surface_container: "#1a2120"

    readonly property color surface_container_high: "#252b2a"

    readonly property color surface_container_highest: "#303635"

    readonly property color surface_container_low: "#161d1c"

    readonly property color surface_container_lowest: "#090f0f"

    readonly property color surface_dim: "#0e1514"

    readonly property color surface_tint: "#81d5cc"

    readonly property color surface_variant: "#3f4947"

    readonly property color tertiary: "#afc9e7"

    readonly property color tertiary_container: "#2f4961"

    readonly property color tertiary_fixed: "#cee5ff"

    readonly property color tertiary_fixed_dim: "#afc9e7"


    // Frutiger Aero / cloudy accents derived from matugen tokens
    readonly property color glassTint:        Qt.rgba(primary_container.r, primary_container.g, primary_container.b, 0.35)
    readonly property color glassHighlight:   Qt.rgba(1, 1, 1, 0.55)
    readonly property color glassEdge:        Qt.rgba(1, 1, 1, 0.75)
    readonly property color glassShadow:      Qt.rgba(0, 0, 0, 0.18)
    readonly property color skyTop:           Qt.lighter(primary_container, 1.15)
    readonly property color skyBottom:        Qt.lighter(tertiary_container, 1.05)
    readonly property color accent:           primary
    readonly property color accentSoft:       inverse_primary
    readonly property color textPrimary:      on_surface
    readonly property color textMuted:        on_surface_variant
}
