$background = rgb(2a2520)
$surface = rgb(352f2a)
$surface_raised = rgb(4d453e)
$surface_overlay = rgb(4d453e)
$text = rgb(ece1d7)
$text_muted = rgb(a38d78)
$accent = rgb(99d59d)
$accent_muted = rgb(78997a)
$accent_alt = rgb(e49b5d)
$on_accent = rgb(2a2520)
$border = rgb(4d453e)
$selection = rgb(4d453e)
$success = rgb(99d59d)
$warning = rgb(ebc06d)
$error = rgb(f17c64)
$info = rgb(ce9bcb)
$shadow = rgb(2a2520)
