return {
  name = "Melange",
  mode = "dark",
  palette = {
    bg1 = "#2A2520",
    bg2 = "#352F2A",
    bg3 = "#4D453E",
    text = "#ECE1D7",
    grey = "#867462",
    muted = "#A38D78",
    accent = "#99D59D",
    accent_muted = "#78997A",
    gold = "#EBC06D",
    orange = "#E49B5D",
    red = "#B65C60",
    magenta = "#CE9BCB",
    blue = "#9AACCE",
    teal = "#86A3A3",
  },
  highlights = {
    Normal = { fg = "text", bg = "bg1" },
    NormalFloat = { fg = "text", bg = "bg2" },
    FloatBorder = { fg = "grey", bg = "bg2" },
    CursorLine = { bg = "bg2" },
    CursorLineNr = { fg = "orange" },
    LineNr = { fg = "grey" },
    SignColumn = { bg = "bg1" },
    ColorColumn = { bg = "bg2" },
    Visual = { bg = "bg3" },
    Search = { fg = "bg1", bg = "orange" },
    IncSearch = { fg = "bg1", bg = "magenta" },
    Pmenu = { fg = "text", bg = "bg2" },
    PmenuSel = { fg = "bg1", bg = "accent" },
    StatusLine = { fg = "text", bg = "bg2" },
    StatusLineNC = { fg = "grey", bg = "bg2" },
    VertSplit = { fg = "grey", bg = "bg1" },
    WinSeparator = { fg = "grey", bg = "bg1" },
  },
}
