return {
  name = "Gruvbox",
  mode = "dark",
  palette = {
    bg0 = "#282828",
    bg1 = "#3c3836",
    bg2 = "#504945",
    bg3 = "#665c54",
    fg1 = "#ebdbb2",
    gray = "#928374",
    red = "#fb4934",
    green = "#b8bb26",
    yellow = "#fabd2f",
    blue = "#83a598",
    purple = "#d3869b",
    aqua = "#8ec07c",
    orange = "#fe8019",
  },
  highlights = {
    Normal = { fg = "fg1", bg = "bg0" },
    NormalFloat = { fg = "fg1", bg = "bg1" },
    FloatBorder = { fg = "gray", bg = "bg1" },
    CursorLine = { bg = "bg1" },
    CursorLineNr = { fg = "orange" },
    LineNr = { fg = "gray" },
    SignColumn = { bg = "bg0" },
    ColorColumn = { bg = "bg1" },
    Visual = { bg = "bg2" },
    Search = { fg = "bg0", bg = "yellow" },
    IncSearch = { fg = "bg0", bg = "orange" },
    Pmenu = { fg = "fg1", bg = "bg1" },
    PmenuSel = { fg = "bg0", bg = "orange" },
    StatusLine = { fg = "fg1", bg = "bg1" },
    StatusLineNC = { fg = "gray", bg = "bg1" },
    VertSplit = { fg = "gray", bg = "bg0" },
    WinSeparator = { fg = "gray", bg = "bg0" },
    Comment = { fg = "gray" },
    Constant = { fg = "purple" },
    String = { fg = "green" },
    Character = { fg = "green" },
    Number = { fg = "purple" },
    Boolean = { fg = "purple" },
    Float = { fg = "purple" },
    Identifier = { fg = "fg1" },
    Function = { fg = "green" },
    Statement = { fg = "red" },
    Conditional = { fg = "red" },
    Repeat = { fg = "red" },
    Label = { fg = "red" },
    Operator = { fg = "red" },
    Keyword = { fg = "red" },
    Exception = { fg = "red" },
    PreProc = { fg = "aqua" },
    Include = { fg = "red" },
    Define = { fg = "aqua" },
    Macro = { fg = "aqua" },
    PreCondit = { fg = "aqua" },
    Type = { fg = "yellow" },
    StorageClass = { fg = "yellow" },
    Structure = { fg = "yellow" },
    Typedef = { fg = "yellow" },
    Special = { fg = "orange" },
    SpecialChar = { fg = "orange" },
    Tag = { fg = "red" },
    Delimiter = { fg = "fg1" },
    SpecialComment = { fg = "aqua" },
    Todo = { fg = "bg0", bg = "yellow" },
    Error = { fg = "red" },
    DiagnosticError = { fg = "red" },
    DiagnosticWarn = { fg = "yellow" },
    DiagnosticInfo = { fg = "blue" },
    DiagnosticHint = { fg = "aqua" },
    DiffAdd = { fg = "green" },
    DiffChange = { fg = "yellow" },
    DiffDelete = { fg = "red" },
    DiffText = { fg = "orange" },
    GitSignsAdd = { fg = "green" },
    GitSignsChange = { fg = "yellow" },
    GitSignsDelete = { fg = "red" },
  },
}
