return {
  name = "Gruvbox",
  mode = "dark",
  palette = {
    bg0 = "#282828",
    bg1 = "#3c3836",
    bg2 = "#504945",
    bg3 = "#665c54",
    fg1 = "#ebdbb2",
    gray = "#928374",
    red = "#fb4934",
    green = "#b8bb26",
    yellow = "#fabd2f",
    blue = "#83a598",
    purple = "#d3869b",
    aqua = "#8ec07c",
    orange = "#fe8019",
  },
  highlights = {
    Normal = { fg = "fg1", bg = "bg0" },
    NormalFloat = { fg = "fg1", bg = "bg1" },
    FloatBorder = { fg = "gray", bg = "bg1" },
    CursorLine = { bg = "bg1" },
    CursorLineNr = { fg = "orange" },
    LineNr = { fg = "gray" },
    SignColumn = { bg = "bg0" },
    ColorColumn = { bg = "bg1" },
    Visual = { bg = "bg3" },
    Search = { fg = "bg0", bg = "yellow" },
    IncSearch = { fg = "bg0", bg = "orange" },
    Pmenu = { fg = "fg1", bg = "bg1" },
    PmenuSel = { fg = "bg0", bg = "orange" },
    StatusLine = { fg = "fg1", bg = "bg1" },
    StatusLineNC = { fg = "gray", bg = "bg1" },
    VertSplit = { fg = "gray", bg = "bg0" },
    WinSeparator = { fg = "gray", bg = "bg0" },
  },
}
