return {
  name = "Rosé Pine",
  mode = "dark",
  palette = {
    base = "#191724",
    surface = "#1f1d2e",
    overlay = "#26233a",
    highlightMed = "#403d52",
    text = "#e0def4",
    subtle = "#908caa",
    love = "#eb6f92",
    gold = "#f6c177",
    rose = "#ebbcba",
    pine = "#31748f",
    foam = "#9ccfd8",
    iris = "#c4a7e7",
  },
  highlights = {
    Normal = { fg = "text", bg = "base" },
    NormalFloat = { fg = "text", bg = "surface" },
    FloatBorder = { fg = "highlightMed", bg = "surface" },
    CursorLine = { bg = "surface" },
    CursorLineNr = { fg = "love" },
    LineNr = { fg = "highlightMed" },
    SignColumn = { bg = "base" },
    ColorColumn = { bg = "surface" },
    Visual = { bg = "overlay" },
    Search = { fg = "base", bg = "gold" },
    IncSearch = { fg = "base", bg = "love" },
    Pmenu = { fg = "text", bg = "surface" },
    PmenuSel = { fg = "base", bg = "love" },
    StatusLine = { fg = "text", bg = "surface" },
    StatusLineNC = { fg = "highlightMed", bg = "surface" },
    VertSplit = { fg = "highlightMed", bg = "base" },
    WinSeparator = { fg = "highlightMed", bg = "base" },
    Comment = { fg = "highlightMed" },
    Constant = { fg = "iris" },
    String = { fg = "pine" },
    Character = { fg = "pine" },
    Number = { fg = "iris" },
    Boolean = { fg = "iris" },
    Float = { fg = "iris" },
    Identifier = { fg = "text" },
    Function = { fg = "love" },
    Statement = { fg = "foam" },
    Conditional = { fg = "foam" },
    Repeat = { fg = "foam" },
    Label = { fg = "foam" },
    Operator = { fg = "foam" },
    Keyword = { fg = "foam" },
    Exception = { fg = "foam" },
    PreProc = { fg = "rose" },
    Include = { fg = "foam" },
    Define = { fg = "rose" },
    Macro = { fg = "rose" },
    PreCondit = { fg = "rose" },
    Type = { fg = "iris" },
    StorageClass = { fg = "iris" },
    Structure = { fg = "iris" },
    Typedef = { fg = "iris" },
    Special = { fg = "gold" },
    SpecialChar = { fg = "gold" },
    Tag = { fg = "foam" },
    Delimiter = { fg = "text" },
    SpecialComment = { fg = "rose" },
    Todo = { fg = "base", bg = "gold" },
    Error = { fg = "love" },
    DiagnosticError = { fg = "love" },
    DiagnosticWarn = { fg = "gold" },
    DiagnosticInfo = { fg = "foam" },
    DiagnosticHint = { fg = "iris" },
    DiffAdd = { fg = "pine" },
    DiffChange = { fg = "gold" },
    DiffDelete = { fg = "love" },
    DiffText = { fg = "love" },
    GitSignsAdd = { fg = "pine" },
    GitSignsChange = { fg = "gold" },
    GitSignsDelete = { fg = "love" },
  },
}
