return {
  name = "Rosé Pine",
  mode = "dark",
  palette = {
    base = "#191724",
    surface = "#1f1d2e",
    overlay = "#26233a",
    highlightMed = "#403d52",
    text = "#e0def4",
    subtle = "#908caa",
    love = "#eb6f92",
    gold = "#f6c177",
    rose = "#ebbcba",
    pine = "#31748f",
    foam = "#9ccfd8",
    iris = "#c4a7e7",
  },
  highlights = {
    Normal = { fg = "text", bg = "base" },
    NormalFloat = { fg = "text", bg = "surface" },
    FloatBorder = { fg = "highlightMed", bg = "surface" },
    CursorLine = { bg = "surface" },
    CursorLineNr = { fg = "love" },
    LineNr = { fg = "highlightMed" },
    SignColumn = { bg = "base" },
    ColorColumn = { bg = "surface" },
    Visual = { bg = "highlightMed" },
    Search = { fg = "base", bg = "gold" },
    IncSearch = { fg = "base", bg = "love" },
    Pmenu = { fg = "text", bg = "surface" },
    PmenuSel = { fg = "base", bg = "love" },
    StatusLine = { fg = "text", bg = "surface" },
    StatusLineNC = { fg = "highlightMed", bg = "surface" },
    VertSplit = { fg = "highlightMed", bg = "base" },
    WinSeparator = { fg = "highlightMed", bg = "base" },
  },
}
