#!/usr/bin/env bash
# =============================================================================
# hyprland-install.sh — Silent package installer for cloudyy-linux
# =============================================================================
# Installs all mandatory + standard packages silently.
# GPU drivers auto-detected via lspci — no prompts.
# Run standalone or called from install.sh.
# Safe to source (functions only; main() guarded by BASH_SOURCE check).
# =============================================================================
set -euo pipefail -E

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DEPS_FILE="${SCRIPT_DIR}/manifest.sh"
readonly LIB_FILE="${SCRIPT_DIR}/../other/lib.sh"

[[ ! -f "$LIB_FILE"  ]] && { echo "[✗] lib.sh not found: ${LIB_FILE}" >&2; exit 1; }
[[ ! -f "$DEPS_FILE" ]] && { echo "[✗] dependencies.conf not found: ${DEPS_FILE}" >&2; exit 1; }

# shellcheck source=install/lib.sh
source "$LIB_FILE"
# shellcheck source=install/dependencies.conf
source "$DEPS_FILE"

[[ $EUID -eq 0 ]] && { log_error "Do not run as root."; exit 1; }

_err_handler() {
  log_error "Unexpected error on line ${BASH_LINENO[0]}: ${BASH_COMMAND}"
  log_error "  in ${BASH_SOURCE[1]:-${BASH_SOURCE[0]}}:${FUNCNAME[1]:-main}"
}
trap '_err_handler' ERR

# =============================================================================
# AUR HELPER
# =============================================================================
setup_aur_helper() {
  log_section "AUR Helper"

  if command -v paru &>/dev/null; then
    AUR_HELPER="paru"; log_ok "Using paru"; return 0
  fi
  if command -v yay &>/dev/null; then
    AUR_HELPER="yay";  log_ok "Using yay";  return 0
  fi

  log "No AUR helper found — installing yay..."
  sudo pacman -S --needed --noconfirm git base-devel

  local tmp
  tmp="$(mktemp -d)"
  trap "rm -rf '${tmp}'" RETURN
  git clone --depth 1 https://aur.archlinux.org/yay.git "${tmp}/yay"
  (cd "${tmp}/yay" && makepkg -si --noconfirm)

  if command -v yay &>/dev/null; then
    AUR_HELPER="yay"
    log_ok "yay installed."
  else
    log_error "Failed to install yay — AUR packages will be skipped."
  fi
}

# =============================================================================
# GPU DETECTION & LAUNCHER
# =============================================================================

# write_gpu_launcher <vendor>
# Generates ~/.config/hypr/cloudyy-launch.sh with GPU-appropriate env vars.
# Vendor: "nvidia" | "nvidia-prime" | "amd" | "intel"
write_gpu_launcher() {
  local vendor="$1"
  local launcher_dir="${HOME}/.config/hypr"
  local launcher="${launcher_dir}/cloudyy-launch.sh"
  local env_d="${HOME}/.config/environment.d"

  mkdir -p "$launcher_dir" "$env_d"

  cat >"$launcher" <<'HEADER'
#!/usr/bin/env bash
# cloudyy-launch.sh — generated by cloudyy-linux installer
# Sets GPU-appropriate Wayland/EGL environment before handing off to Hyprland.
HEADER

  case "$vendor" in
  nvidia)
    cat >>"$launcher" <<'NVIDIA'
# Resolve DRM card node at launch time (survives reboots with shifting indices)
_drm_node="$(ls /dev/dri/by-path/*-card 2>/dev/null | head -1)"
[[ -n "$_drm_node" ]] && export AQ_DRM_DEVICES="$_drm_node"

export LIBVA_DRIVER_NAME=nvidia
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1
export NVD_BACKEND=direct
# Note: __EGL_VENDOR_LIBRARY_FILENAMES intentionally omitted —
# GLVND expects a JSON vendor config path, not a .so path.
NVIDIA

    cat >"${env_d}/nvidia-wayland.conf" <<'ENVD'
LIBVA_DRIVER_NAME=nvidia
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
NVD_BACKEND=direct
ENVD
    log_ok "NVIDIA environment.d entry written."
    ;;
  nvidia-prime)
    # Hybrid Intel+NVIDIA: PRIME render offload — renders on NVIDIA, displays via Intel
    cat >>"$launcher" <<'PRIME'
export __NV_PRIME_RENDER_OFFLOAD=1
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export LIBVA_DRIVER_NAME=iHD
export WLR_NO_HARDWARE_CURSORS=1
PRIME
    cat >"${env_d}/nvidia-prime-wayland.conf" <<'PRIMEENVD'
__NV_PRIME_RENDER_OFFLOAD=1
__NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
__GLX_VENDOR_LIBRARY_NAME=nvidia
LIBVA_DRIVER_NAME=iHD
WLR_NO_HARDWARE_CURSORS=1
PRIMEENVD
    log_ok "NVIDIA PRIME (hybrid) launcher + environment.d written."
    ;;
  amd)
    cat >>"$launcher" <<'AMD'
export LIBVA_DRIVER_NAME=radeonsi
AMD
    ;;
  intel)
    cat >>"$launcher" <<'INTEL'
# iHD for Gen9+ (Broadwell+); i965 for older hardware
if command -v vainfo &>/dev/null; then
  vainfo 2>&1 | grep -q iHD \
    && export LIBVA_DRIVER_NAME=iHD \
    || export LIBVA_DRIVER_NAME=i965
else
  export LIBVA_DRIVER_NAME=iHD
fi
INTEL
    ;;
  esac

  # Universal Wayland block (appended for all vendors)
  cat >>"$launcher" <<'WAYLAND'

export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
export ELECTRON_OZONE_PLATFORM_HINT=auto

exec uwsm start hyprland.desktop
WAYLAND

  chmod +x "$launcher"
  log_ok "GPU launcher written: ${launcher}"
}

detect_and_install_gpu() {
  log_section "GPU Drivers"

  local gpu_info
  gpu_info="$(lspci 2>/dev/null | grep -iE 'vga|3d|display' || true)"

  if [[ -z "$gpu_info" ]]; then
    log_warn "No GPU detected (VM or unknown hardware) — skipping GPU drivers."
    return 0
  fi

  local has_nvidia=0 has_amd=0 has_intel=0
  echo "$gpu_info" | grep -qi "nvidia"      && has_nvidia=1 || true
  echo "$gpu_info" | grep -qi "amd\|radeon" && has_amd=1   || true
  echo "$gpu_info" | grep -qi "intel"       && has_intel=1  || true

  local primary_vendor=""

  # Install all detected GPU drivers first
  (( has_nvidia )) && { log "Detected NVIDIA — installing drivers..."; pacman_install "NVIDIA" "${OFFICIAL_GPU_NVIDIA[@]}"; }
  (( has_amd ))    && { log "Detected AMD — installing drivers...";    pacman_install "AMD"    "${OFFICIAL_GPU_AMD[@]}"; }
  (( has_intel ))  && { log "Detected Intel — installing drivers...";  pacman_install "Intel"  "${OFFICIAL_GPU_INTEL[@]}"; }

  # Select launcher: hybrid Intel+NVIDIA → PRIME offload; else first detected wins
  if   (( has_nvidia && has_intel )); then
    log "Hybrid Intel+NVIDIA detected — using PRIME offload launcher."
    primary_vendor="nvidia-prime"
  elif (( has_nvidia )); then primary_vendor="nvidia"
  elif (( has_amd ));    then primary_vendor="amd"
  elif (( has_intel ));  then primary_vendor="intel"
  fi

  [[ -n "$primary_vendor" ]] && write_gpu_launcher "$primary_vendor"
  log_ok "GPU drivers installed."
}

# =============================================================================
# EXTERNAL PACKAGES
# =============================================================================
install_stochos() {
  local installer
  installer="$(mktemp)"
  trap 'rm -f "$installer"' RETURN

  log "Downloading the Stochos installer..."
  curl -fsSL --connect-timeout 10 --max-time 60 \
    https://raw.githubusercontent.com/museslabs/stochos/main/install.sh \
    -o "$installer"
  sh "$installer"

  command -v stochos &>/dev/null || {
    log_error "Stochos installation completed but the command is not on PATH."
    return 1
  }
  log_ok "Stochos installed."
}

# =============================================================================
# POST-INSTALL CONFIGURATION
# =============================================================================
configure_zram() {
  command -v zram-generator &>/dev/null || return 0
  local conf="/etc/systemd/zram-generator.conf"
  [[ -f "$conf" ]] && { log_skip "ZRAM already configured."; return 0; }
  log "Configuring ZRAM..."
  printf '[zram0]\nzram-size = min(ram / 2, 8192)\ncompression-algorithm = zstd\n' \
    | sudo tee "$conf" >/dev/null
  sudo systemctl daemon-reload
  sudo systemctl start "systemd-zram-setup@zram0.service" 2>/dev/null || true
  log_ok "ZRAM configured."
}

configure_bluetooth() {
  if pacman -Qi bluez &>/dev/null; then
    sudo systemctl enable --now bluetooth.service 2>/dev/null || true
    log_ok "Bluetooth service enabled."
  fi
}

# =============================================================================
# MAIN
# =============================================================================
main() {
  log_section "System Update"
  sudo pacman -Syu --noconfirm
  log_ok "System up to date."

  setup_aur_helper

  log_section "Installing — Mandatory Packages"
  pacman_install "Compositor" "${MANDATORY_OFFICIAL_COMPOSITOR[@]}"
  pacman_install "Daemons"    "${MANDATORY_OFFICIAL_DAEMONS[@]}"
  pacman_install "Audio"      "${MANDATORY_OFFICIAL_AUDIO[@]}"
  pacman_install "Interface"  "${MANDATORY_OFFICIAL_INTERFACE[@]}"
  pacman_install "Screenshot" "${MANDATORY_OFFICIAL_SCREENSHOT[@]}"
  pacman_install "Shell"      "${MANDATORY_OFFICIAL_SHELL[@]}"
  pacman_install "System"     "${MANDATORY_OFFICIAL_SYSTEM[@]}"
  pacman_install "Theming"    "${MANDATORY_OFFICIAL_THEMING[@]}"
  pacman_install "Monitoring" "${MANDATORY_OFFICIAL_MONITORING[@]}"
  aur_install    "Daemons"    "${MANDATORY_AUR_DAEMONS[@]}"
  aur_install    "Interface"  "${MANDATORY_AUR_INTERFACE[@]}"
  aur_install    "Theming"    "${MANDATORY_AUR_THEMING[@]}"
  aur_install    "Monitoring" "${MANDATORY_AUR_MONITORING[@]}"
  deploy_system_monitor
  verify_system_monitor
  aur_install    "Cloudyy"    "${MANDATORY_AUR_CLOUDYY[@]}"

  log_section "Installing — Standard Packages"
  pacman_install "Standard" "${STANDARD_INSTALL_OFFICIAL[@]}"
  aur_install    "Standard" "${STANDARD_INSTALL_AUR[@]}"
  if ! bash "${SCRIPT_DIR}/zen-live-theme.sh" install; then
    log_warn "Zen live-theme bridge unavailable; browser colors will not follow Cloudyy themes until it installs."
  fi

  log_section "Installing — External Packages"
  install_stochos

  configure_zram
  configure_bluetooth

  log_ok "All packages installed."
}

[[ "${BASH_SOURCE[0]}" == "$0" ]] && main "$@" || true
