#!/usr/bin/env bash
# =============================================================================
# setup-system-theme.sh — Configure System-Wide Light/Dark Mode Integration
# =============================================================================
# Sets up GTK/Qt/XDG Portal theme integration to make light/dark mode changes
# apply system-wide. Called by deploy-dotfiles.sh during main setup.
#
# This script:
# - Updates shell RC files to source theme environment variables
# - Creates necessary directories and config files
# =============================================================================

set -euo pipefail -E

# --- Colors (TTY-aware) ---
if [[ -t 1 ]]; then
  RED=$'\e[1;31m' GREEN=$'\e[1;32m' YELLOW=$'\e[1;33m'
  BLUE=$'\e[1;34m' CYAN=$'\e[1;36m' BOLD=$'\e[1m' RESET=$'\e[0m'
else
  RED='' GREEN='' YELLOW='' BLUE='' CYAN='' BOLD='' RESET=''
fi

# --- Logging ---
_ts() { date '+%H:%M:%S'; }
log()         { printf '%s[*]%s  [%s] %s\n'               "$BLUE"   "$RESET" "$(_ts)" "$1"; }
log_ok()      { printf '%s[✓]%s  [%s] %s\n'               "$GREEN"  "$RESET" "$(_ts)" "$1"; }
log_warn()    { printf '%s[!]%s  [%s] %s\n'               "$YELLOW" "$RESET" "$(_ts)" "$1"; }
log_error()   { printf '%s[✗]%s  [%s] %s\n'               "$RED"    "$RESET" "$(_ts)" "$1" >&2; }
log_skip()    { printf '%s[-]%s  [%s] %s %s(skipped)%s\n' "$CYAN"   "$RESET" "$(_ts)" "$1" "$YELLOW" "$RESET"; }
log_section() { printf '\n%s%s── %s%s\n'                   "$BOLD"   "$CYAN"  "$1"     "$RESET"; }

_err_handler() {
  log_error "Unexpected error on line ${BASH_LINENO[0]}: ${BASH_COMMAND}"
  log_error "  in ${BASH_SOURCE[1]:-${BASH_SOURCE[0]}}:${FUNCNAME[1]:-main}"
}
trap '_err_handler' ERR

# --- Configuration ---
readonly SYSTEM_THEME_ENV="${HOME}/.config/hypr/theme_state/system_theme.env"
readonly SHELL_THEME_BEGIN="# >>> cloudyy-linux system theme >>>"
readonly SHELL_THEME_END="# <<< cloudyy-linux system theme <<<"

# --- Helpers ---

# Check if a line exists in a file
line_exists() {
  local line="$1"
  local file="$2"
  [[ -f "$file" ]] && grep -Fx "$line" "$file" >/dev/null 2>&1
}

# Append shell RC setup if not already present
add_to_shell_rc() {
  local rc_file="$1"

  [[ -f "$rc_file" ]] || touch "$rc_file"

  if grep -Fq "$SHELL_THEME_BEGIN" "$rc_file" 2>/dev/null; then
    log_skip "Shell setup already present in $(basename "$rc_file")"
    return 0
  fi

  cat >>"$rc_file" <<EOF

${SHELL_THEME_BEGIN}
# Apply system theme environment variables (cloudyy-linux)
if [[ -f "${HOME}/.config/hypr/theme_state/system_theme.env" ]]; then
  # shellcheck source=/dev/null
  source "${HOME}/.config/hypr/theme_state/system_theme.env"
fi

# Ensure Qt uses appropriate theme
export QT_QPA_PLATFORMTHEME="${QT_QPA_PLATFORMTHEME:-kvantum}"
${SHELL_THEME_END}
EOF

  log_ok "Updated $(basename "$rc_file")"
}

# =============================================================================
# SETUP STEPS
# =============================================================================

setup_theme_env_file() {
  log_section "Theme Environment File"

  local env_dir
  env_dir="$(dirname "$SYSTEM_THEME_ENV")"

  if [[ ! -d "$env_dir" ]]; then
    mkdir -p "$env_dir"
    log_ok "Created directory: $env_dir"
  fi

  if [[ -f "$SYSTEM_THEME_ENV" ]]; then
    log_skip "Theme environment file already exists"
  else
    # Initialize with dark mode default
    cat >"$SYSTEM_THEME_ENV" <<'EOF'
# Auto-generated by setup-system-theme.sh
# Source this in your shell RC files to apply system theme environment variables
export GTK_THEME_VARIANT="dark"
export QT_STYLE_OVERRIDE="kvantum-dark"
export COLORFGBG="0;7"
EOF
    log_ok "Created theme environment file: $SYSTEM_THEME_ENV"
  fi
}

setup_shell_rc_files() {
  log_section "Shell RC Files"

  local -a rc_files=("${HOME}/.zshrc" "${HOME}/.bashrc")
  local updated=0

  for rc_file in "${rc_files[@]}"; do
    if [[ -f "$rc_file" || ! -e "$rc_file" ]]; then # File exists or can be created
      add_to_shell_rc "$rc_file"
      ((++updated))
    fi
  done

  if ((updated > 0)); then
    log_ok "Shell RC files configured ($updated updated)"
  fi
}

show_next_steps() {
  log_section "Next Steps"

  printf '\n%sTo activate system theme integration immediately, run:%s\n\n' "$BOLD" "$RESET"
  printf '  Reload shell RC:\n'
  printf '     %ssource ~/.zshrc%s  (or %ssource ~/.bashrc%s if using bash)\n\n' "$BOLD" "$RESET" "$BOLD" "$RESET"

  printf '%sThen test the integration:%s\n' "$YELLOW" "$RESET"
  printf '  %scloudyy-theme toggle%s\n\n' "$BOLD" "$RESET"

  printf 'For more information, see:\n'
  printf '  %s~/.config/hypr/THEME_QUICKSTART.md%s\n' "$BOLD" "$RESET"
}

# =============================================================================
# MAIN
# =============================================================================

main() {
  printf '\n%s%s── System Theme Integration Setup ──%s\n\n' "$BOLD" "$CYAN" "$RESET"

  setup_theme_env_file
  setup_shell_rc_files

  printf '\n%s[✓] System theme integration setup complete!%s\n' "$GREEN" "$RESET"

  show_next_steps
}

# Only run main if script is executed directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
