# Cloud Center — static geolocation source
[wifi]
enable=false

[3g]
enable=false

[cdma]
enable=false

[modem-gps]
enable=false

[network-nmea]
enable=false

[ip]
enable=false

[static-source]
enable=true
