general {
    lock_cmd = cloudyy-lock
    before_sleep_cmd = cloudyy-lock
}

listener {
    timeout = 900
    on-timeout = cloudyy-idle show
    on-resume = cloudyy-idle dismiss
}

listener {
    timeout = 2700
    on-timeout = cloudyy-lock
}

listener {
    timeout = 3600
    on-timeout = true # systemctl suspend
}
