return {
  name = "Monochrome",
  mode = "dark",
  palette = {
    base = "#050505",
    surface = "#0d0d0d",
    overlay = "#1a1a1a",
    selection = "#3a3a3a",
    muted = "#888888",
    dim = "#9a9a9a",
    mid = "#b0b0b0",
    light = "#c9c9c9",
    bright = "#d6d6d6",
    text = "#f2f2f2",
    accent = "#ffffff",
  },
  highlights = {
    Normal = { fg = "text", bg = "base" },
    NormalFloat = { fg = "text", bg = "surface" },
    FloatBorder = { fg = "muted", bg = "surface" },
    CursorLine = { bg = "surface" },
    CursorLineNr = { fg = "accent" },
    LineNr = { fg = "muted" },
    SignColumn = { bg = "base" },
    ColorColumn = { bg = "surface" },
    Visual = { bg = "selection" },
    Search = { fg = "base", bg = "bright" },
    IncSearch = { fg = "base", bg = "accent" },
    Pmenu = { fg = "text", bg = "surface" },
    PmenuSel = { fg = "base", bg = "accent" },
    StatusLine = { fg = "text", bg = "surface" },
    StatusLineNC = { fg = "muted", bg = "surface" },
    VertSplit = { fg = "muted", bg = "base" },
    WinSeparator = { fg = "muted", bg = "base" },
  },
}
