return {
  name = "Monochrome",
  mode = "dark",
  palette = {
    base = "#050505",
    surface = "#0d0d0d",
    overlay = "#1a1a1a",
    muted = "#888888",
    dim = "#9a9a9a",
    mid = "#b0b0b0",
    light = "#c9c9c9",
    bright = "#d6d6d6",
    text = "#f2f2f2",
    accent = "#ffffff",
  },
  highlights = {
    Normal = { fg = "text", bg = "base" },
    NormalFloat = { fg = "text", bg = "surface" },
    FloatBorder = { fg = "muted", bg = "surface" },
    CursorLine = { bg = "surface" },
    CursorLineNr = { fg = "accent" },
    LineNr = { fg = "muted" },
    SignColumn = { bg = "base" },
    ColorColumn = { bg = "surface" },
    Visual = { bg = "overlay" },
    Search = { fg = "base", bg = "bright" },
    IncSearch = { fg = "base", bg = "accent" },
    Pmenu = { fg = "text", bg = "surface" },
    PmenuSel = { fg = "base", bg = "accent" },
    StatusLine = { fg = "text", bg = "surface" },
    StatusLineNC = { fg = "muted", bg = "surface" },
    VertSplit = { fg = "muted", bg = "base" },
    WinSeparator = { fg = "muted", bg = "base" },
    Comment = { fg = "muted" },
    Constant = { fg = "mid" },
    String = { fg = "mid" },
    Character = { fg = "light" },
    Number = { fg = "mid" },
    Boolean = { fg = "mid" },
    Float = { fg = "mid" },
    Identifier = { fg = "text" },
    Function = { fg = "light" },
    Statement = { fg = "accent" },
    Conditional = { fg = "accent" },
    Repeat = { fg = "accent" },
    Label = { fg = "accent" },
    Operator = { fg = "accent" },
    Keyword = { fg = "accent" },
    Exception = { fg = "accent" },
    PreProc = { fg = "bright" },
    Include = { fg = "accent" },
    Define = { fg = "bright" },
    Macro = { fg = "bright" },
    PreCondit = { fg = "bright" },
    Type = { fg = "light" },
    StorageClass = { fg = "light" },
    Structure = { fg = "light" },
    Typedef = { fg = "light" },
    Special = { fg = "bright" },
    SpecialChar = { fg = "bright" },
    Tag = { fg = "accent" },
    Delimiter = { fg = "text" },
    SpecialComment = { fg = "muted" },
    Todo = { fg = "base", bg = "bright" },
    Error = { fg = "accent" },
    DiagnosticError = { fg = "accent" },
    DiagnosticWarn = { fg = "bright" },
    DiagnosticInfo = { fg = "light" },
    DiagnosticHint = { fg = "muted" },
    DiffAdd = { fg = "bright" },
    DiffChange = { fg = "light" },
    DiffDelete = { fg = "muted" },
    DiffText = { fg = "accent" },
    GitSignsAdd = { fg = "bright" },
    GitSignsChange = { fg = "light" },
    GitSignsDelete = { fg = "accent" },
  },
}
