return {
  name = "Nord",
  mode = "dark",
  palette = {
    nord0 = "#2E3440",
    nord1 = "#3B4252",
    nord2 = "#434C5E",
    nord3 = "#4C566A",
    nord4 = "#D8DEE9",
    nord5 = "#E5E9F0",
    nord6 = "#ECEFF4",
    nord7 = "#8FBCBB",
    nord8 = "#88C0D0",
    nord9 = "#81A1C1",
    nord10 = "#5E81AC",
    nord11 = "#BF616A",
    nord12 = "#D08770",
    nord13 = "#EBCB8B",
    nord14 = "#A3BE8C",
    nord15 = "#B48EAD",
  },
  highlights = {
    Normal = { fg = "nord4", bg = "nord0" },
    NormalFloat = { fg = "nord4", bg = "nord1" },
    FloatBorder = { fg = "nord3", bg = "nord1" },
    CursorLine = { bg = "nord1" },
    CursorLineNr = { fg = "nord8" },
    LineNr = { fg = "nord3" },
    SignColumn = { bg = "nord0" },
    ColorColumn = { bg = "nord1" },
    Visual = { bg = "nord3" },
    Search = { fg = "nord0", bg = "nord13" },
    IncSearch = { fg = "nord0", bg = "nord8" },
    Pmenu = { fg = "nord4", bg = "nord1" },
    PmenuSel = { fg = "nord0", bg = "nord8" },
    StatusLine = { fg = "nord4", bg = "nord1" },
    StatusLineNC = { fg = "nord3", bg = "nord1" },
    VertSplit = { fg = "nord3", bg = "nord0" },
    WinSeparator = { fg = "nord3", bg = "nord0" },
  },
}
