return {
  name = "Nord",
  mode = "dark",
  palette = {
    nord0 = "#2E3440",
    nord1 = "#3B4252",
    nord2 = "#434C5E",
    nord3 = "#4C566A",
    nord4 = "#D8DEE9",
    nord5 = "#E5E9F0",
    nord6 = "#ECEFF4",
    nord7 = "#8FBCBB",
    nord8 = "#88C0D0",
    nord9 = "#81A1C1",
    nord10 = "#5E81AC",
    nord11 = "#BF616A",
    nord12 = "#D08770",
    nord13 = "#EBCB8B",
    nord14 = "#A3BE8C",
    nord15 = "#B48EAD",
  },
  highlights = {
    Normal = { fg = "nord4", bg = "nord0" },
    NormalFloat = { fg = "nord4", bg = "nord1" },
    FloatBorder = { fg = "nord3", bg = "nord1" },
    CursorLine = { bg = "nord1" },
    CursorLineNr = { fg = "nord8" },
    LineNr = { fg = "nord3" },
    SignColumn = { bg = "nord0" },
    ColorColumn = { bg = "nord1" },
    Visual = { bg = "nord2" },
    Search = { fg = "nord0", bg = "nord13" },
    IncSearch = { fg = "nord0", bg = "nord8" },
    Pmenu = { fg = "nord4", bg = "nord1" },
    PmenuSel = { fg = "nord0", bg = "nord8" },
    StatusLine = { fg = "nord4", bg = "nord1" },
    StatusLineNC = { fg = "nord3", bg = "nord1" },
    VertSplit = { fg = "nord3", bg = "nord0" },
    WinSeparator = { fg = "nord3", bg = "nord0" },
    Comment = { fg = "nord3" },
    Constant = { fg = "nord15" },
    String = { fg = "nord14" },
    Character = { fg = "nord14" },
    Number = { fg = "nord15" },
    Boolean = { fg = "nord15" },
    Float = { fg = "nord15" },
    Identifier = { fg = "nord4" },
    Function = { fg = "nord8" },
    Statement = { fg = "nord9" },
    Conditional = { fg = "nord9" },
    Repeat = { fg = "nord9" },
    Label = { fg = "nord9" },
    Operator = { fg = "nord9" },
    Keyword = { fg = "nord9" },
    Exception = { fg = "nord9" },
    PreProc = { fg = "nord10" },
    Include = { fg = "nord9" },
    Define = { fg = "nord10" },
    Macro = { fg = "nord10" },
    PreCondit = { fg = "nord10" },
    Type = { fg = "nord7" },
    StorageClass = { fg = "nord7" },
    Structure = { fg = "nord7" },
    Typedef = { fg = "nord7" },
    Special = { fg = "nord13" },
    SpecialChar = { fg = "nord13" },
    Tag = { fg = "nord9" },
    Delimiter = { fg = "nord6" },
    SpecialComment = { fg = "nord10" },
    Todo = { fg = "nord0", bg = "nord13" },
    Error = { fg = "nord11" },
    DiagnosticError = { fg = "nord11" },
    DiagnosticWarn = { fg = "nord13" },
    DiagnosticInfo = { fg = "nord9" },
    DiagnosticHint = { fg = "nord7" },
    DiffAdd = { fg = "nord14" },
    DiffChange = { fg = "nord13" },
    DiffDelete = { fg = "nord11" },
    DiffText = { fg = "nord8" },
    GitSignsAdd = { fg = "nord14" },
    GitSignsChange = { fg = "nord13" },
    GitSignsDelete = { fg = "nord11" },
  },
}
