$image = "/home/schultz/cloudyyOS/Wallpapers/19.png"

$background = rgba(131314ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(303031ff)

$inverse_primary = rgba(575f6bff)

$inverse_surface = rgba(e4e2e3ff)

$on_background = rgba(e4e2e3ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(29313cff)

$on_primary_container = rgba(dce3f2ff)

$on_primary_fixed = rgba(151c26ff)

$on_primary_fixed_variant = rgba(404753ff)

$on_secondary = rgba(2c3137ff)

$on_secondary_container = rgba(dfe2ebff)

$on_secondary_fixed = rgba(181c22ff)

$on_secondary_fixed_variant = rgba(43474eff)

$on_surface = rgba(e4e2e3ff)

$on_surface_variant = rgba(c8c6c7ff)

$on_tertiary = rgba(263141ff)

$on_tertiary_container = rgba(d8e3f8ff)

$on_tertiary_fixed = rgba(111c2bff)

$on_tertiary_fixed_variant = rgba(3c4758ff)

$outline = rgba(919092ff)

$outline_variant = rgba(474648ff)

$primary = rgba(c0c7d5ff)

$primary_container = rgba(404753ff)

$primary_fixed = rgba(dce3f2ff)

$primary_fixed_dim = rgba(c0c7d5ff)

$scrim = rgba(000000ff)

$secondary = rgba(c3c6cfff)

$secondary_container = rgba(43474eff)

$secondary_fixed = rgba(dfe2ebff)

$secondary_fixed_dim = rgba(c3c6cfff)

$shadow = rgba(000000ff)

$source_color = rgba(6281abff)

$surface = rgba(131314ff)

$surface_bright = rgba(39393aff)

$surface_container = rgba(1f1f21ff)

$surface_container_high = rgba(2a2a2bff)

$surface_container_highest = rgba(353536ff)

$surface_container_low = rgba(1b1b1dff)

$surface_container_lowest = rgba(0e0e0fff)

$surface_dim = rgba(131314ff)

$surface_tint = rgba(c0c7d5ff)

$surface_variant = rgba(474648ff)

$tertiary = rgba(bcc7dbff)

$tertiary_container = rgba(3c4758ff)

$tertiary_fixed = rgba(d8e3f8ff)

$tertiary_fixed_dim = rgba(bcc7dbff)

