$image = "/home/schultz/dots/Wallpapers/158.png"

$background = rgba(161217ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(342f34ff)

$inverse_primary = rgba(794f82ff)

$inverse_surface = rgba(eae0e7ff)

$on_background = rgba(eae0e7ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(462151ff)

$on_primary_container = rgba(fbd7ffff)

$on_primary_fixed = rgba(2f0a3aff)

$on_primary_fixed_variant = rgba(5f3869ff)

$on_secondary = rgba(3a2b3dff)

$on_secondary_container = rgba(f3dbf3ff)

$on_secondary_fixed = rgba(241727ff)

$on_secondary_fixed_variant = rgba(524154ff)

$on_surface = rgba(eae0e7ff)

$on_surface_variant = rgba(cfc3cdff)

$on_tertiary = rgba(4c2522ff)

$on_tertiary_container = rgba(ffdad6ff)

$on_tertiary_fixed = rgba(33110eff)

$on_tertiary_fixed_variant = rgba(673b37ff)

$outline = rgba(988e97ff)

$outline_variant = rgba(4c444cff)

$primary = rgba(e8b6f0ff)

$primary_container = rgba(5f3869ff)

$primary_fixed = rgba(fbd7ffff)

$primary_fixed_dim = rgba(e8b6f0ff)

$scrim = rgba(000000ff)

$secondary = rgba(d6c0d6ff)

$secondary_container = rgba(524154ff)

$secondary_fixed = rgba(f3dbf3ff)

$secondary_fixed_dim = rgba(d6c0d6ff)

$shadow = rgba(000000ff)

$source_color = rgba(ca3df4ff)

$surface = rgba(161217ff)

$surface_bright = rgba(3d373dff)

$surface_container = rgba(231e23ff)

$surface_container_high = rgba(2e282eff)

$surface_container_highest = rgba(393338ff)

$surface_container_low = rgba(1f1a1fff)

$surface_container_lowest = rgba(110d12ff)

$surface_dim = rgba(161217ff)

$surface_tint = rgba(e8b6f0ff)

$surface_variant = rgba(4c444cff)

$tertiary = rgba(f5b7b1ff)

$tertiary_container = rgba(673b37ff)

$tertiary_fixed = rgba(ffdad6ff)

$tertiary_fixed_dim = rgba(f5b7b1ff)

