#!/usr/bin/env bash
# cloudyy-launch.sh — generated by cloudyy-linux installer
# Sets GPU-appropriate Wayland/EGL environment before handing off to Hyprland.
# Re-generated on each install/reinstall — edit hyprland-install.sh to persist
# custom changes.

# ── NVIDIA ────────────────────────────────────────────────────────────────────
_drm_node="$(ls /dev/dri/card* 2>/dev/null | head -1)"
export LIBVA_DRIVER_NAME=nvidia
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __GL_GSYNC_ALLOWED=0
export __GL_VRR_ALLOWED=0
export WLR_NO_HARDWARE_CURSORS=1
export NVD_BACKEND=direct
[[ -n "$_drm_node" ]] && export AQ_DRM_DEVICES="$_drm_node"

# ── Universal Wayland/XDG ─────────────────────────────────────────────────────
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export MOZ_ENABLE_WAYLAND=1

exec Hyprland
