general {
    lock_cmd = cloudyy-lock
    before_sleep_cmd = cloudyy-lock
}

listener {
    timeout = 7200
    on-timeout = true
    on-resume = cloudyy-idle dismiss
}

listener {
    timeout = 14400
    on-timeout = cloudyy-lock
}
