# colour importing
source = ~/.config/matugen/generated/hyprcolors.conf
source = ~/.config/hypr/source/lookandfeel.conf

# General sourcing

source = ~/.config/hypr/user-configs/user_monitors.conf
source = ~/.config/hypr/user-configs/userbinds.conf
source = ~/.config/hypr/user-configs/user_input.conf
source = ~/.config/hypr/source/windowrules.conf

# Animations

source = ~/.config/hypr/source/animations.conf

# autostart

source = ~/.config/hypr/source/autostart.conf
