# colour importing
source = ~/.config/matugen/generated/hyprcolors.conf
source = ~/.config/hypr/source/lookandfeel.conf

# General sourcing

source = ~/.config/hypr/source/monitors.conf
source = ~/.config/hypr/source/bindings.conf
source = ~/.config/hypr/source/input.conf
source = ~/.config/hypr/source/windowrules.conf

# Animations

source = ~/.config/hypr/source/animations.conf

# autostart

source = ~/.config/hypr/source/autostart.conf


