background #333c43
foreground #d3c6aa
cursor #d3c6aa
cursor_text_color #333c43
selection_background #4d5960
selection_foreground #d3c6aa
url_color #a7c080

color0 #3a464c
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d699b6
color6 #a7c080
color7 #859289
color8 #4d5960
color9 #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #7fbbb3
color15 #d3c6aa
