return {
  name = "Everforest",
  mode = "dark",
  palette = {
    bg0 = "#333c43",
    bg1 = "#3a464c",
    bg2 = "#434f55",
    fg = "#d3c6aa",
    grey0 = "#7a8478",
    grey1 = "#859289",
    red = "#e67e80",
    orange = "#e69875",
    yellow = "#dbbc7f",
    green = "#a7c080",
    aqua = "#83c092",
    blue = "#7fbbb3",
    purple = "#d699b6",
  },
  highlights = {
    Normal = { fg = "fg", bg = "bg0" },
    NormalFloat = { fg = "fg", bg = "bg1" },
    FloatBorder = { fg = "grey0", bg = "bg1" },
    CursorLine = { bg = "bg1" },
    CursorLineNr = { fg = "green" },
    LineNr = { fg = "grey0" },
    SignColumn = { bg = "bg0" },
    ColorColumn = { bg = "bg1" },
    Visual = { bg = "bg2" },
    Search = { fg = "bg0", bg = "yellow" },
    IncSearch = { fg = "bg0", bg = "green" },
    Pmenu = { fg = "fg", bg = "bg1" },
    PmenuSel = { fg = "bg0", bg = "green" },
    StatusLine = { fg = "fg", bg = "bg1" },
    StatusLineNC = { fg = "grey0", bg = "bg1" },
    VertSplit = { fg = "grey0", bg = "bg0" },
    WinSeparator = { fg = "grey0", bg = "bg0" },
    Comment = { fg = "grey1" },
    Constant = { fg = "purple" },
    String = { fg = "green" },
    Character = { fg = "green" },
    Number = { fg = "purple" },
    Boolean = { fg = "purple" },
    Float = { fg = "purple" },
    Identifier = { fg = "fg" },
    Function = { fg = "green" },
    Statement = { fg = "red" },
    Conditional = { fg = "red" },
    Repeat = { fg = "red" },
    Label = { fg = "red" },
    Operator = { fg = "red" },
    Keyword = { fg = "red" },
    Exception = { fg = "red" },
    PreProc = { fg = "aqua" },
    Include = { fg = "red" },
    Define = { fg = "aqua" },
    Macro = { fg = "aqua" },
    PreCondit = { fg = "aqua" },
    Type = { fg = "yellow" },
    StorageClass = { fg = "yellow" },
    Structure = { fg = "yellow" },
    Typedef = { fg = "yellow" },
    Special = { fg = "orange" },
    SpecialChar = { fg = "orange" },
    Tag = { fg = "red" },
    Delimiter = { fg = "fg" },
    SpecialComment = { fg = "aqua" },
    Todo = { fg = "bg0", bg = "yellow" },
    Error = { fg = "red" },
    DiagnosticError = { fg = "red" },
    DiagnosticWarn = { fg = "yellow" },
    DiagnosticInfo = { fg = "blue" },
    DiagnosticHint = { fg = "aqua" },
    DiffAdd = { fg = "green" },
    DiffChange = { fg = "yellow" },
    DiffDelete = { fg = "red" },
    DiffText = { fg = "orange" },
    GitSignsAdd = { fg = "green" },
    GitSignsChange = { fg = "yellow" },
    GitSignsDelete = { fg = "red" },
  },
}
