return {
  name = "Everforest",
  mode = "dark",
  palette = {
    bg0 = "#333c43",
    bg1 = "#3a464c",
    bg2 = "#434f55",
    fg = "#d3c6aa",
    grey0 = "#7a8478",
    grey1 = "#859289",
    red = "#e67e80",
    orange = "#e69875",
    yellow = "#dbbc7f",
    green = "#a7c080",
    aqua = "#83c092",
    blue = "#7fbbb3",
    purple = "#d699b6",
  },
  highlights = {
    Normal = { fg = "fg", bg = "bg0" },
    NormalFloat = { fg = "fg", bg = "bg1" },
    FloatBorder = { fg = "grey0", bg = "bg1" },
    CursorLine = { bg = "bg1" },
    CursorLineNr = { fg = "green" },
    LineNr = { fg = "grey0" },
    SignColumn = { bg = "bg0" },
    ColorColumn = { bg = "bg1" },
    Visual = { bg = "bg2" },
    Search = { fg = "bg0", bg = "yellow" },
    IncSearch = { fg = "bg0", bg = "green" },
    Pmenu = { fg = "fg", bg = "bg1" },
    PmenuSel = { fg = "bg0", bg = "green" },
    StatusLine = { fg = "fg", bg = "bg1" },
    StatusLineNC = { fg = "grey0", bg = "bg1" },
    VertSplit = { fg = "grey0", bg = "bg0" },
    WinSeparator = { fg = "grey0", bg = "bg0" },
  },
}
