# --- CC: Window Rules ---
# --- CC: End Window Rules ---

# --- CC: Layer Rules ---
# --- CC: End Layer Rules ---

# --- CC: Autostart ---
hl.exec_once("waybar")
# --- CC: End Autostart ---

# --- CC: Environment ---
hl.env("XCURSOR_THEME", "Bibata")
# --- CC: End Environment ---
