#!/usr/bin/env bash
# =============================================================================
# hyprland-install.sh — Silent package installer for cloudyy-linux
# =============================================================================
# Installs all mandatory + standard packages silently.
# GPU drivers auto-detected via lspci — no prompts.
# Run standalone or called from install.sh.
# Safe to source (functions only; main() guarded by BASH_SOURCE check).
# =============================================================================
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DEPS_FILE="${SCRIPT_DIR}/dependencies.conf"
readonly LIB_FILE="${SCRIPT_DIR}/lib.sh"

[[ ! -f "$LIB_FILE"  ]] && { echo "[✗] lib.sh not found: ${LIB_FILE}" >&2; exit 1; }
[[ ! -f "$DEPS_FILE" ]] && { echo "[✗] dependencies.conf not found: ${DEPS_FILE}" >&2; exit 1; }

# shellcheck source=install/lib.sh
source "$LIB_FILE"
# shellcheck source=install/dependencies.conf
source "$DEPS_FILE"

[[ $EUID -eq 0 ]] && { log_error "Do not run as root."; exit 1; }

# =============================================================================
# AUR HELPER
# =============================================================================
setup_aur_helper() {
  log_section "AUR Helper"

  if command -v paru &>/dev/null; then
    AUR_HELPER="paru"; log_ok "Using paru"; return 0
  fi
  if command -v yay &>/dev/null; then
    AUR_HELPER="yay";  log_ok "Using yay";  return 0
  fi

  log "No AUR helper found — installing yay..."
  sudo pacman -S --needed --noconfirm git base-devel

  local tmp
  tmp="$(mktemp -d)"
  trap "rm -rf '${tmp}'" RETURN
  git clone --depth 1 https://aur.archlinux.org/yay.git "${tmp}/yay"
  (cd "${tmp}/yay" && makepkg -si --noconfirm)

  if command -v yay &>/dev/null; then
    AUR_HELPER="yay"
    log_ok "yay installed."
  else
    log_error "Failed to install yay — AUR packages will be skipped."
  fi
}

# =============================================================================
# GPU DETECTION & LAUNCHER
# =============================================================================

# write_gpu_launcher <vendor>
# Generates ~/.config/hypr/cloudyy-launch.sh with GPU-appropriate env vars.
# Vendor: "nvidia" | "amd" | "intel"
write_gpu_launcher() {
  local vendor="$1"
  local launcher_dir="${HOME}/.config/hypr"
  local launcher="${launcher_dir}/cloudyy-launch.sh"
  local hypr_conf="${HOME}/.config/hypr/hyprland.conf"
  local env_d="${HOME}/.config/environment.d"

  mkdir -p "$launcher_dir" "$env_d"

  cat >"$launcher" <<'HEADER'
#!/usr/bin/env bash
# cloudyy-launch.sh — generated by cloudyy-linux installer
# Sets GPU-appropriate Wayland/EGL environment before handing off to Hyprland.
HEADER

  case "$vendor" in
  nvidia)
    cat >>"$launcher" <<'NVIDIA'
# Resolve DRM card node at launch time (survives reboots with shifting indices)
_drm_node="$(ls /dev/dri/by-path/*-card 2>/dev/null | head -1)"
[[ -n "$_drm_node" ]] && export AQ_DRM_DEVICES="$_drm_node"

export LIBVA_DRIVER_NAME=nvidia
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1
export NVD_BACKEND=direct
# Note: __EGL_VENDOR_LIBRARY_FILENAMES intentionally omitted —
# GLVND expects a JSON vendor config path, not a .so path.
NVIDIA

    cat >"${env_d}/nvidia-wayland.conf" <<'ENVD'
LIBVA_DRIVER_NAME=nvidia
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
NVD_BACKEND=direct
ENVD
    log_ok "NVIDIA environment.d entry written."
    ;;
  amd)
    cat >>"$launcher" <<'AMD'
export LIBVA_DRIVER_NAME=radeonsi
AMD
    ;;
  intel)
    cat >>"$launcher" <<'INTEL'
# iHD for Gen9+ (Broadwell+); i965 for older hardware
if command -v vainfo &>/dev/null; then
  vainfo 2>&1 | grep -q iHD \
    && export LIBVA_DRIVER_NAME=iHD \
    || export LIBVA_DRIVER_NAME=i965
else
  export LIBVA_DRIVER_NAME=iHD
fi
INTEL
    ;;
  esac

  # Universal Wayland block (appended for all vendors)
  cat >>"$launcher" <<'WAYLAND'

export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
export ELECTRON_OZONE_PLATFORM_HINT=auto

exec uwsm start hyprland.desktop
WAYLAND

  chmod +x "$launcher"
  log_ok "GPU launcher written: ${launcher}"

  # Inject env block into hyprland.conf (idempotent)
  if [[ -f "$hypr_conf" ]] && ! grep -q "# cloudyy-gpu-env" "$hypr_conf"; then
    printf '\n# cloudyy-gpu-env\nsource = %s\n' "$launcher" >>"$hypr_conf"
    log_ok "Launcher registered in hyprland.conf."
  else
    log_skip "GPU env block already present in hyprland.conf."
  fi
}

detect_and_install_gpu() {
  log_section "GPU Drivers"

  local gpu_info
  gpu_info="$(lspci 2>/dev/null | grep -iE 'vga|3d|display' || true)"

  if [[ -z "$gpu_info" ]]; then
    log_warn "No GPU detected (VM or unknown hardware) — skipping GPU drivers."
    return 0
  fi

  local has_nvidia=0 has_amd=0 has_intel=0
  echo "$gpu_info" | grep -qi "nvidia"      && has_nvidia=1 || true
  echo "$gpu_info" | grep -qi "amd\|radeon" && has_amd=1   || true
  echo "$gpu_info" | grep -qi "intel"       && has_intel=1  || true

  local primary_vendor=""

  if (( has_nvidia )); then
    log "Detected NVIDIA — installing drivers..."
    pacman_install "NVIDIA" "${OFFICIAL_GPU_NVIDIA[@]}"
    primary_vendor="nvidia"
  fi
  if (( has_amd )); then
    log "Detected AMD — installing drivers..."
    pacman_install "AMD" "${OFFICIAL_GPU_AMD[@]}"
    [[ -z "$primary_vendor" ]] && primary_vendor="amd"
  fi
  if (( has_intel )); then
    log "Detected Intel — installing drivers..."
    pacman_install "Intel" "${OFFICIAL_GPU_INTEL[@]}"
    [[ -z "$primary_vendor" ]] && primary_vendor="intel"
  fi

  [[ -n "$primary_vendor" ]] && write_gpu_launcher "$primary_vendor"
  log_ok "GPU drivers installed."
}

# =============================================================================
# POST-INSTALL CONFIGURATION
# =============================================================================
configure_zram() {
  command -v zram-generator &>/dev/null || return 0
  local conf="/etc/systemd/zram-generator.conf"
  [[ -f "$conf" ]] && { log_skip "ZRAM already configured."; return 0; }
  log "Configuring ZRAM..."
  printf '[zram0]\nzram-size = min(ram / 2, 8192)\ncompression-algorithm = zstd\n' \
    | sudo tee "$conf" >/dev/null
  sudo systemctl daemon-reload
  sudo systemctl start "systemd-zram-setup@zram0.service" 2>/dev/null || true
  log_ok "ZRAM configured."
}

configure_bluetooth() {
  if pacman -Qi bluez &>/dev/null; then
    sudo systemctl enable --now bluetooth.service 2>/dev/null || true
    log_ok "Bluetooth service enabled."
  fi
}

# =============================================================================
# MAIN
# =============================================================================
main() {
  log_section "System Update"
  sudo pacman -Syu --noconfirm
  log_ok "System up to date."

  setup_aur_helper
  detect_and_install_gpu

  log_section "Installing — Mandatory Packages"
  pacman_install "Compositor" "${MANDATORY_OFFICIAL_COMPOSITOR[@]}"
  pacman_install "Daemons"    "${MANDATORY_OFFICIAL_DAEMONS[@]}"
  pacman_install "Audio"      "${MANDATORY_OFFICIAL_AUDIO[@]}"
  pacman_install "Interface"  "${MANDATORY_OFFICIAL_INTERFACE[@]}"
  pacman_install "Screenshot" "${MANDATORY_OFFICIAL_SCREENSHOT[@]}"
  pacman_install "Shell"      "${MANDATORY_OFFICIAL_SHELL[@]}"
  pacman_install "System"     "${MANDATORY_OFFICIAL_SYSTEM[@]}"
  pacman_install "Theming"    "${MANDATORY_OFFICIAL_THEMING[@]}"
  pacman_install "Monitoring" "${MANDATORY_OFFICIAL_MONITORING[@]}"
  aur_install    "Daemons"    "${MANDATORY_AUR_DAEMONS[@]}"
  aur_install    "Interface"  "${MANDATORY_AUR_INTERFACE[@]}"
  aur_install    "Theming"    "${MANDATORY_AUR_THEMING[@]}"

  log_section "Installing — Standard Packages"
  pacman_install "Standard" "${STANDARD_INSTALL_OFFICIAL[@]}"
  aur_install    "Standard" "${STANDARD_INSTALL_AUR[@]}"

  configure_zram
  configure_bluetooth

  log_ok "All packages installed."
}

[[ "${BASH_SOURCE[0]}" == "$0" ]] && main "$@"
