#!/usr/bin/env bash
# setup-keyring.sh — Automates GNOME Keyring unlocking for hyprlock

set -euo pipefail

# --- Colors ------------------------------------------------------------------
if [[ -t 1 ]]; then
  GREEN=$'\e[1;32m' BLUE=$'\e[1;34m' RESET=$'\e[0m'
else
  GREEN='' BLUE='' RESET=''
fi

log() { printf '%s[*]%s %s\n' "$BLUE" "$RESET" "$1"; }
log_ok() { printf '%s[✓]%s %s\n' "$GREEN" "$RESET" "$1"; }

# ── Configure PAM for hyprlock ──────────────────────────────────────────────
log "Configuring PAM to unlock GNOME Keyring via hyprlock..."

# We create/overwrite /etc/pam.d/hyprlock with the necessary modules.
# This ensures that when the user enters their password in hyprlock,
# it's passed to pam_gnome_keyring.so.
sudo tee /etc/pam.d/hyprlock >/dev/null <<PAM_EOF
# PAM configuration file for hyprlock
# Generated by cloudyy-linux installer

auth      include   system-auth
auth      optional  pam_gnome_keyring.so

account   include   system-auth

password  include   system-auth

session   include   system-auth
session   optional  pam_gnome_keyring.so auto_start
PAM_EOF

log_ok "PAM configuration for hyprlock updated."

# ── Sync Keyring password with User password ─────────────────────────────────
log "Configuring PAM to sync Keyring password with system password..."

# We inject pam_gnome_keyring.so into /etc/pam.d/passwd so that if the user
# runs `passwd` in the future, the keyring password updates automatically.
if ! grep -q "pam_gnome_keyring.so" /etc/pam.d/passwd 2>/dev/null; then
  echo "password        optional        pam_gnome_keyring.so" | sudo tee -a /etc/pam.d/passwd > /dev/null
  log_ok "Password sync configured in /etc/pam.d/passwd."
else
  log_ok "Password sync already configured."
fi
