#!/usr/bin/env bash
# =============================================================================
# setup-system-theme.sh — Configure System-Wide Light/Dark Mode Integration
# =============================================================================
# Sets up GTK/Qt/XDG Portal theme integration to make light/dark mode changes
# apply system-wide. Called by deploy-dotfiles.sh during main setup.
#
# This script:
# - Enables the systemd service for theme auto-apply on login
# - Updates shell RC files to source theme environment variables
# - Creates necessary directories and config files
# =============================================================================

set -euo pipefail

# --- Colors (TTY-aware) ---
if [[ -t 1 ]]; then
  RED=$'\e[1;31m' GREEN=$'\e[1;32m' YELLOW=$'\e[1;33m'
  BLUE=$'\e[1;34m' CYAN=$'\e[1;36m' BOLD=$'\e[1m' RESET=$'\e[0m'
else
  RED='' GREEN='' YELLOW='' BLUE='' CYAN='' BOLD='' RESET=''
fi

# --- Logging ---
log() { printf '%s[*]%s %s\n' "$BLUE" "$RESET" "$1"; }
log_ok() { printf '%s[✓]%s %s\n' "$GREEN" "$RESET" "$1"; }
log_warn() { printf '%s[!]%s %s\n' "$YELLOW" "$RESET" "$1"; }
log_error() { printf '%s[✗]%s %s\n' "$RED" "$RESET" "$1" >&2; }
log_skip() { printf '%s[-]%s %s %s(skipped)%s\n' "$CYAN" "$RESET" "$1" "$YELLOW" "$RESET"; }
log_section() {
  printf '\n%s%s── %s%s\n' "$BOLD" "$CYAN" "$1" "$RESET"
}

# --- Configuration ---
readonly SYSTEM_THEME_ENV="${HOME}/.config/hypr/theme_state/system_theme.env"
readonly SYSTEMD_SERVICE="${HOME}/.config/systemd/user/apply-system-theme.service"
readonly HYPR_CONFIG="${HOME}/.config/hypr/hyprland.conf"
readonly SHELL_THEME_BEGIN="# >>> cloudyy-linux system theme >>>"
readonly SHELL_THEME_END="# <<< cloudyy-linux system theme <<<"

# --- Helpers ---

systemctl_available() {
  command -v systemctl >/dev/null 2>&1 &&
    systemctl --user show-environment >/dev/null 2>&1
}

# Check if a line exists in a file
line_exists() {
  local line="$1"
  local file="$2"
  [[ -f "$file" ]] && grep -Fx "$line" "$file" >/dev/null 2>&1
}

# Append shell RC setup if not already present
add_to_shell_rc() {
  local rc_file="$1"

  [[ -f "$rc_file" ]] || touch "$rc_file"

  if grep -Fq "$SHELL_THEME_BEGIN" "$rc_file" 2>/dev/null; then
    log_skip "Shell setup already present in $(basename "$rc_file")"
    return 0
  fi

  cat >>"$rc_file" <<EOF

    ${SHELL_THEME_BEGIN}
    # Apply system theme environment variables (cloudyy-linux)
if [[ -f "${HOME}/.config/hypr/theme_state/system_theme.env" ]]; then
  # shellcheck source=/dev/null
  source "${HOME}/.config/hypr/theme_state/system_theme.env"
fi

# Ensure Qt uses appropriate theme
export QT_QPA_PLATFORMTHEME="${QT_QPA_PLATFORMTHEME:-kvantum}"
    ${SHELL_THEME_END}
EOF

  log_ok "Updated $(basename "$rc_file")"
}

# =============================================================================
# SETUP STEPS
# =============================================================================

setup_theme_env_file() {
  log_section "Theme Environment File"

  local env_dir
  env_dir="$(dirname "$SYSTEM_THEME_ENV")"

  if [[ ! -d "$env_dir" ]]; then
    mkdir -p "$env_dir"
    log_ok "Created directory: $env_dir"
  fi

  if [[ -f "$SYSTEM_THEME_ENV" ]]; then
    log_skip "Theme environment file already exists"
  else
    # Initialize with dark mode default
    cat >"$SYSTEM_THEME_ENV" <<'EOF'
# Auto-generated by setup-system-theme.sh
# Source this in your shell RC files to apply system theme environment variables
export GTK_THEME_VARIANT="dark"
export QT_STYLE_OVERRIDE="kvantum-dark"
export COLORFGBG="0;7"
EOF
    log_ok "Created theme environment file: $SYSTEM_THEME_ENV"
  fi
}

setup_systemd_service() {
  log_section "Systemd Service"

  if ! systemctl_available; then
    log_warn "systemctl --user not available (might be running in a container or special environment)"
    log_warn "Skipping systemd service setup — theme will apply on next shell launch instead"
    return 0
  fi

  local service_dir
  service_dir="$(dirname "$SYSTEMD_SERVICE")"
  mkdir -p "$service_dir"

  if [[ -f "$SYSTEMD_SERVICE" ]]; then
    log_skip "Systemd service already exists"
  else
    log_ok "Systemd service path prepared: $service_dir"
  fi

  # Try to enable the service
  if systemctl --user list-unit-files 2>/dev/null | grep -q "apply-system-theme"; then
    log "Systemd service found, is it enabled?"
    if systemctl --user is-enabled apply-system-theme.service >/dev/null 2>&1; then
      log_ok "Systemd service already enabled"
    else
      log "Attempting to enable apply-system-theme.service..."
      if systemctl --user enable apply-system-theme.service 2>/dev/null; then
        log_ok "Systemd service enabled"
        if systemctl --user start apply-system-theme.service 2>/dev/null; then
          log_ok "Systemd service started"
        fi
      else
        log_warn "Could not enable via systemctl (might need manual setup later)"
      fi
    fi
  else
    log_warn "Systemd service not yet created — it will be available after files are in place"
    log "You can enable it manually with:"
    printf "  %ssystemctl --user enable apply-system-theme.service%s\n" "$BOLD" "$RESET"
  fi
}

setup_shell_rc_files() {
  log_section "Shell RC Files"

  local -a rc_files=("${HOME}/.zshrc" "${HOME}/.bashrc")
  local updated=0

  for rc_file in "${rc_files[@]}"; do
    if [[ -f "$rc_file" || ! -e "$rc_file" ]]; then # File exists or can be created
      add_to_shell_rc "$rc_file"
      ((++updated))
    fi
  done

  if ((updated > 0)); then
    log_ok "Shell RC files configured ($updated updated)"
  fi
}

setup_hyprland_integration() {
  log_section "Hyprland Config (Optional)"

  if [[ ! -f "$HYPR_CONFIG" ]]; then
    log_skip "Hyprland config not found (might not be installed)"
    return 0
  fi

  # Check if theme restore is already in config
  if grep -q "theme_controller.*restore" "$HYPR_CONFIG" 2>/dev/null; then
    log_skip "Hyprland theme integration already configured"
    return 0
  fi

  log_warn "Optional: Add theme auto-apply to Hyprland config?"
  log "This will add: exec-once = ~/cloudyy_scripts/theme_controller.sh restore"

  read -rp "Add to Hyprland config? [Y/n]: " _confirm
  if [[ "${_confirm,,}" != "n" ]]; then
    cat >>"$HYPR_CONFIG" <<'EOF'

# cloudyy-linux: Restore last used theme + wallpaper on startup
exec-once = ~/cloudyy_scripts/theme_controller.sh restore
EOF
    log_ok "Added theme auto-restore to Hyprland config"
  else
    log_skip "Hyprland theme integration not added (can be done manually later)"
  fi
}

show_next_steps() {
  log_section "Next Steps"

  printf '\n%sTo activate system theme integration immediately, run:%s\n\n' "$BOLD" "$RESET"
  printf '  1. Reload shell RC:\n'
  printf '     %ssource ~/.zshrc%s  (or %ssource ~/.bashrc%s if using bash)\n\n' "$BOLD" "$RESET" "$BOLD" "$RESET"

  if ! systemctl_available; then
    printf '  2. Enable systemd service (when systemctl is available):\n'
    printf '     %ssystemctl --user enable apply-system-theme.service%s\n' "$BOLD" "$RESET"
  else
    printf '  2. (Systemd service should already be handling auto-apply)\n'
  fi

  printf '\n%sThen test the integration:%s\n' "$BOLD" "$RESET"
  printf '  %s~/cloudyy_scripts/theme_controller.sh toggle%s\n\n' "$BOLD" "$RESET"

  printf 'For more information, see:\n'
  printf '  %s~/.config/hypr/THEME_QUICKSTART.md%s\n' "$BOLD" "$RESET"
}

# =============================================================================
# MAIN
# =============================================================================

main() {
  printf '\n%s%s── System Theme Integration Setup ──%s\n\n' "$BOLD" "$CYAN" "$RESET"

  setup_theme_env_file
  setup_systemd_service
  setup_shell_rc_files
  setup_hyprland_integration

  printf '\n%s[✓] System theme integration setup complete!%s\n' "$GREEN" "$RESET"

  show_next_steps
}

# Only run main if script is executed directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
