#!/usr/bin/env bash
# setup-ssh.sh — SSH key and hyprlock PAM hook setup
#
# Writes /etc/pam.d/hyprlock so the SSH key is automatically loaded when
# the screen is unlocked, then guides the user through setting the SSH key
# passphrase to match their login password.
#
# Safe to re-run at any time. Can be run standalone or called by install.sh.

set -euo pipefail -E

# --- Colors ------------------------------------------------------------------
if [[ -t 1 ]]; then
  RED=$'\e[1;31m' GREEN=$'\e[1;32m' YELLOW=$'\e[1;33m'
  BLUE=$'\e[1;34m' BOLD=$'\e[1m' RESET=$'\e[0m'
else
  RED='' GREEN='' YELLOW='' BLUE='' BOLD='' RESET=''
fi

_ts() { date '+%H:%M:%S'; }
log()       { printf '%s[*]%s  [%s] %s\n' "$BLUE"   "$RESET" "$(_ts)" "$1"; }
log_ok()    { printf '%s[✓]%s  [%s] %s\n' "$GREEN"  "$RESET" "$(_ts)" "$1"; }
log_warn()  { printf '%s[!]%s  [%s] %s\n' "$YELLOW" "$RESET" "$(_ts)" "$1"; }
log_error() { printf '%s[✗]%s  [%s] %s\n' "$RED"    "$RESET" "$(_ts)" "$1" >&2; }

_err_handler() {
  log_error "Unexpected error on line ${BASH_LINENO[0]}: ${BASH_COMMAND}"
  log_error "  in ${BASH_SOURCE[1]:-${BASH_SOURCE[0]}}:${FUNCNAME[1]:-main}"
}
trap '_err_handler' ERR

# --- Sudo --------------------------------------------------------------------
# install.sh holds a sudo heartbeat; only prompt when running standalone.
if [[ "${CLOUDYY_INSTALL_ORCHESTRATED:-0}" != "1" ]]; then
  log "Requesting sudo for PAM configuration..."
  sudo -v
fi

# ── PAM: hyprlock ─────────────────────────────────────────────────────────────
log "Configuring hyprlock PAM (gnome-keyring + SSH key hook)..."

sudo tee /etc/pam.d/hyprlock >/dev/null <<PAM_EOF
# PAM configuration file for hyprlock
# Generated by cloudyy-linux installer

auth      include   system-auth
auth      optional  pam_gnome_keyring.so
auth      optional  pam_exec.so expose_authtok ${HOME}/cloudyy_scripts/ssh-pam-load.sh

account   include   system-auth

password  include   system-auth

session   include   system-auth
session   optional  pam_gnome_keyring.so auto_start
PAM_EOF

log_ok "hyprlock PAM configured."

# ── SSH key passphrase ────────────────────────────────────────────────────────
# Skip in unattended mode — user must run this manually after first boot.
if [[ "${CLOUDYY_UNATTENDED:-0}" == "1" ]]; then
  log_warn "Unattended mode — skipping SSH key passphrase setup."
  log_warn "After first boot, run: ~/cloudyy_scripts/ssh-auth.sh --setup"
  exit 0
fi

mkdir -p "${HOME}/.ssh"
chmod 700 "${HOME}/.ssh"

printf '\n%s SSH Key Setup %s\n' "$BOLD" "$RESET"
printf 'For automatic SSH key loading on screen unlock, your SSH key\n'
printf 'passphrase must match your login password.\n\n'

if [[ ! -f "${HOME}/.ssh/id_ed25519" ]]; then
  printf '%sNo key found%s — generating ~/.ssh/id_ed25519.\n' "$YELLOW" "$RESET"
  printf '%sUse your login password as the passphrase.%s\n\n' "$BOLD" "$RESET"
  ssh-keygen -t ed25519 -f "${HOME}/.ssh/id_ed25519" -C "$(whoami)@$(hostname)"
  log_ok "SSH key generated."
else
  printf '%sExisting key found%s — updating passphrase.\n' "$YELLOW" "$RESET"
  printf '%sSet the new passphrase to your login password.%s\n\n' "$BOLD" "$RESET"
  ssh-keygen -p -f "${HOME}/.ssh/id_ed25519"
  log_ok "SSH key passphrase updated."
fi
