# Matugen btop template
# Theme: #ffb3ad

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1a1111"

# Main text color
theme[main_fg]="#f1dedd"

# Title color for boxes
theme[title]="#ffb3ad"

# Highlight color for listview items
theme[hi_fg]="#571e1b"

# Background color of selected item in processes box
theme[selected_bg]="#ffb3ad"

# Foreground color of selected item in processes box
theme[selected_fg]="#571e1b"

# Color of inactive/disabled text
theme[inactive_fg]="#a08c8a"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#d8c2bf"

# Background color of the percentage meters
theme[meter_bg]="#3d3231"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e7bdb9"

# Cpu box outline color
theme[cpu_box]="#534342"

# Memory box outline color
theme[mem_box]="#534342"

# Net box outline color
theme[net_box]="#534342"

# Processes box outline color
theme[proc_box]="#534342"

# Box divider line and small boxes line color
theme[div_line]="#534342"

# Temperature graph colors
theme[temp_start]="#ffb3ad"
theme[temp_mid]="#e7bdb9"
theme[temp_end]="#e1c28c"

# CPU graph colors
theme[cpu_start]="#ffb3ad"
theme[cpu_mid]="#e7bdb9"
theme[cpu_end]="#e1c28c"

# Mem/Disk free meter
theme[free_start]="#e7bdb9"
theme[free_mid]="#e7bdb9"
theme[free_end]="#e1c28c"

# Mem/Disk cached meter
theme[cached_start]="#e7bdb9"
theme[cached_mid]="#e7bdb9"
theme[cached_end]="#e1c28c"

# Mem/Disk available meter
theme[available_start]="#e1c28c"
theme[available_mid]="#e1c28c"
theme[available_end]="#ffb3ad"

# Mem/Disk used meter
theme[used_start]="#ffb3ad"
theme[used_mid]="#ffb3ad"
theme[used_end]="#e7bdb9"

# Download graph colors
theme[download_start]="#ffb3ad"
theme[download_mid]="#e7bdb9"
theme[download_end]="#e1c28c"

# Upload graph colors
theme[upload_start]="#e1c28c"
theme[upload_mid]="#e7bdb9"
theme[upload_end]="#ffb3ad"
