# Matugen btop template
# Theme: #b6c4ff

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#121318"

# Main text color
theme[main_fg]="#e3e1e9"

# Title color for boxes
theme[title]="#b6c4ff"

# Highlight color for listview items
theme[hi_fg]="#1d2d61"

# Background color of selected item in processes box
theme[selected_bg]="#b6c4ff"

# Foreground color of selected item in processes box
theme[selected_fg]="#1d2d61"

# Color of inactive/disabled text
theme[inactive_fg]="#90909a"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#c6c5d0"

# Background color of the percentage meters
theme[meter_bg]="#34343a"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c2c5dd"

# Cpu box outline color
theme[cpu_box]="#45464f"

# Memory box outline color
theme[mem_box]="#45464f"

# Net box outline color
theme[net_box]="#45464f"

# Processes box outline color
theme[proc_box]="#45464f"

# Box divider line and small boxes line color
theme[div_line]="#45464f"

# Temperature graph colors
theme[temp_start]="#b6c4ff"
theme[temp_mid]="#c2c5dd"
theme[temp_end]="#e3bada"

# CPU graph colors
theme[cpu_start]="#b6c4ff"
theme[cpu_mid]="#c2c5dd"
theme[cpu_end]="#e3bada"

# Mem/Disk free meter
theme[free_start]="#c2c5dd"
theme[free_mid]="#c2c5dd"
theme[free_end]="#e3bada"

# Mem/Disk cached meter
theme[cached_start]="#c2c5dd"
theme[cached_mid]="#c2c5dd"
theme[cached_end]="#e3bada"

# Mem/Disk available meter
theme[available_start]="#e3bada"
theme[available_mid]="#e3bada"
theme[available_end]="#b6c4ff"

# Mem/Disk used meter
theme[used_start]="#b6c4ff"
theme[used_mid]="#b6c4ff"
theme[used_end]="#c2c5dd"

# Download graph colors
theme[download_start]="#b6c4ff"
theme[download_mid]="#c2c5dd"
theme[download_end]="#e3bada"

# Upload graph colors
theme[upload_start]="#e3bada"
theme[upload_mid]="#c2c5dd"
theme[upload_end]="#b6c4ff"
