TITLE="Welcome to Cloudyy"
SUBTITLE="The basic set up is ready, this page will help you settle in"
KEYBINDS_TITLE="Keybinds"
KEYBINDS_SUB="See how to control your desktop"
CLOUDCENTER_TITLE="Explore Cloud Center"
CLOUDCENTER_SUB="Global settings menu, adjust theme, change wallpapers and other settings"
UPDATE_TITLE="Run system update"
UPDATE_SUB="Your system may be behind on packages"
