return {
  name = "Vantablack",
  mode = "dark",
  palette = {
    base = "#050505",
    surface = "#0d0d0d",
    overlay = "#1a1a1a",
    selection = "#3a3a3a",
    muted = "#888888",
    text = "#f2f2f2",
    crimson = "#ff2d55",
    cyan = "#00d4ff",
    lightCyan = "#64d2ff",
    green = "#30d158",
    yellow = "#ffd60a",
    red = "#ff453a",
    purple = "#bf5af2",
    orange = "#ff9f0a",
  },
  highlights = {
    Normal = { fg = "text", bg = "base" },
    NormalFloat = { fg = "text", bg = "surface" },
    FloatBorder = { fg = "muted", bg = "surface" },
    CursorLine = { bg = "surface" },
    CursorLineNr = { fg = "crimson" },
    LineNr = { fg = "muted" },
    SignColumn = { bg = "base" },
    ColorColumn = { bg = "surface" },
    Visual = { bg = "selection" },
    Search = { fg = "base", bg = "yellow" },
    IncSearch = { fg = "base", bg = "crimson" },
    Pmenu = { fg = "text", bg = "surface" },
    PmenuSel = { fg = "base", bg = "crimson" },
    StatusLine = { fg = "text", bg = "surface" },
    StatusLineNC = { fg = "muted", bg = "surface" },
    VertSplit = { fg = "muted", bg = "base" },
    WinSeparator = { fg = "muted", bg = "base" },
  },
}
