return {
  name = "Vantablack",
  mode = "dark",
  palette = {
    base = "#050505",
    surface = "#0d0d0d",
    overlay = "#1a1a1a",
    muted = "#888888",
    text = "#f2f2f2",
    crimson = "#ff2d55",
    cyan = "#00d4ff",
    lightCyan = "#64d2ff",
    green = "#30d158",
    yellow = "#ffd60a",
    red = "#ff453a",
    purple = "#bf5af2",
    orange = "#ff9f0a",
  },
  highlights = {
    Normal = { fg = "text", bg = "base" },
    NormalFloat = { fg = "text", bg = "surface" },
    FloatBorder = { fg = "muted", bg = "surface" },
    CursorLine = { bg = "surface" },
    CursorLineNr = { fg = "crimson" },
    LineNr = { fg = "muted" },
    SignColumn = { bg = "base" },
    ColorColumn = { bg = "surface" },
    Visual = { bg = "overlay" },
    Search = { fg = "base", bg = "yellow" },
    IncSearch = { fg = "base", bg = "crimson" },
    Pmenu = { fg = "text", bg = "surface" },
    PmenuSel = { fg = "base", bg = "crimson" },
    StatusLine = { fg = "text", bg = "surface" },
    StatusLineNC = { fg = "muted", bg = "surface" },
    VertSplit = { fg = "muted", bg = "base" },
    WinSeparator = { fg = "muted", bg = "base" },
    Comment = { fg = "muted" },
    Constant = { fg = "purple" },
    String = { fg = "green" },
    Character = { fg = "green" },
    Number = { fg = "purple" },
    Boolean = { fg = "purple" },
    Float = { fg = "purple" },
    Identifier = { fg = "text" },
    Function = { fg = "cyan" },
    Statement = { fg = "crimson" },
    Conditional = { fg = "crimson" },
    Repeat = { fg = "crimson" },
    Label = { fg = "crimson" },
    Operator = { fg = "crimson" },
    Keyword = { fg = "crimson" },
    Exception = { fg = "crimson" },
    PreProc = { fg = "purple" },
    Include = { fg = "crimson" },
    Define = { fg = "purple" },
    Macro = { fg = "purple" },
    PreCondit = { fg = "purple" },
    Type = { fg = "lightCyan" },
    StorageClass = { fg = "lightCyan" },
    Structure = { fg = "lightCyan" },
    Typedef = { fg = "lightCyan" },
    Special = { fg = "orange" },
    SpecialChar = { fg = "orange" },
    Tag = { fg = "crimson" },
    Delimiter = { fg = "text" },
    SpecialComment = { fg = "purple" },
    Todo = { fg = "base", bg = "yellow" },
    Error = { fg = "red" },
    DiagnosticError = { fg = "red" },
    DiagnosticWarn = { fg = "yellow" },
    DiagnosticInfo = { fg = "lightCyan" },
    DiagnosticHint = { fg = "cyan" },
    DiffAdd = { fg = "green" },
    DiffChange = { fg = "yellow" },
    DiffDelete = { fg = "red" },
    DiffText = { fg = "orange" },
    GitSignsAdd = { fg = "green" },
    GitSignsChange = { fg = "yellow" },
    GitSignsDelete = { fg = "red" },
  },
}
