return {
  name = "Celestial Ice",
  mode = "light",
  palette = {
    bg0 = "#f4f9ff",
    bg1 = "#e8f3fe",
    bg2 = "#d8e5f7",
    bg3 = "#aac3cf",
    fg1 = "#2a3d45",
    gray = "#5b7282",
    red = "#bb3d56",
    green = "#327a4b",
    yellow = "#976008",
    blue = "#22749c",
    purple = "#6a5bb8",
    aqua = "#2a8a80",
    orange = "#2f6fb0",
  },
  highlights = {
    Normal = { fg = "fg1", bg = "bg0" },
    NormalFloat = { fg = "fg1", bg = "bg1" },
    FloatBorder = { fg = "gray", bg = "bg1" },
    CursorLine = { bg = "bg1" },
    CursorLineNr = { fg = "orange" },
    LineNr = { fg = "gray" },
    SignColumn = { bg = "bg0" },
    ColorColumn = { bg = "bg1" },
    Visual = { bg = "bg3" },
    Search = { fg = "bg0", bg = "yellow" },
    IncSearch = { fg = "bg0", bg = "orange" },
    Pmenu = { fg = "fg1", bg = "bg1" },
    PmenuSel = { fg = "bg0", bg = "orange" },
    StatusLine = { fg = "fg1", bg = "bg1" },
    StatusLineNC = { fg = "gray", bg = "bg1" },
    VertSplit = { fg = "gray", bg = "bg0" },
    WinSeparator = { fg = "gray", bg = "bg0" },
  },
}
