#--------------------------------------------------------------#
# Edit configs here. And the source them inside of 
# /hypr/hyprland.conf
#
#--------------------------------------------------------------#
#
