-- Shared variables and environment
-- Sources: source/variables.conf + legacy env.lua

terminal = "kitty"
browser = "zen-browser"
mainMod = "SUPER"
fileManager = "nautilus"

hl.env("BROWSER", browser)
hl.env("TERMINAL", terminal)
hl.env("FILEMANAGER", fileManager)
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")

-- GPU environment vars are set by ~/.config/hypr/cloudyy-launch.sh (generated by the
-- installer per-system). Do not hardcode GPU vars here — they vary by hardware.

-- @cloud-center-rules-startup-state = {"env_vars": []}

-- --- Cloud Center managed additions ---
-- --- End Cloud Center managed additions ---
