pragma Singleton
import QtQuick

// Generated by matugen. Do not edit by hand.
QtObject {
    readonly property string mode: "{{ colors.background.default.hex }}" === "#fff8f8" ? "light" : "auto"

<* for name, value in colors *>
    readonly property color {{name}}: "{{value.default.hex}}"
<* endfor *>

    // Frutiger Aero / cloudy accents derived from matugen tokens
    readonly property color glassTint:        Qt.rgba(primary_container.r, primary_container.g, primary_container.b, 0.35)
    readonly property color glassHighlight:   Qt.rgba(1, 1, 1, 0.55)
    readonly property color glassEdge:        Qt.rgba(1, 1, 1, 0.75)
    readonly property color glassShadow:      Qt.rgba(0, 0, 0, 0.18)
    readonly property color skyTop:           Qt.lighter(primary_container, 1.15)
    readonly property color skyBottom:        Qt.lighter(tertiary_container, 1.05)
    readonly property color accent:           primary
    readonly property color accentSoft:       inverse_primary
    readonly property color textPrimary:      on_surface
    readonly property color textMuted:        on_surface_variant
}
