-- Shared variables and environment
-- Sources: source/variables.conf + legacy env.lua

terminal = "kitty"
browser = "zen-browser"
mainMod = "SUPER"
fileManager = "nautilus"

hl.env("BROWSER", browser)
hl.env("TERMINAL", terminal)
hl.env("FILEMANAGER", fileManager)

-- GPU environment vars are set by ~/.config/hypr/cloudyy-launch.sh (generated by the
-- installer per-system). Do not hardcode GPU vars here — they vary by hardware.
